version: '3.7'

services:
  db:
    image: mongo
    container_name: data-pipeline-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - "./data.csv:/home/data.csv"
    command: >
      bash -c "
      mongod --fork --logpath /var/log/mongodb.log &&
      mongoimport --db mydatabase --collection data_collection --type csv --file /home/data.csv --headerline &&
      tail -f /dev/null"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"

volumes:
  mongodb_data:
