version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nestjs-network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    volumes:
      - ./src:/usr/src/app/src  
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestdb
    networks:
      - nestjs-network

volumes:
  mongo_data:

networks:
  nestjs-network:
    driver: bridge
